### ISSUE TITLE
Making use of YAML specification

### ISSUE THREAD

**Issue by danielwilms** [GENIVI/vehicle_signal_specification#149]
Right now, every file is specified as a plain list, which creates some issues:
1. Instead of an object, each spec file is defined as a list of single objects
2. Nesting is impossible, which leads to repetition in the definition
3. Creates `None` types

Here's one example (it comes from the real spec, but is changed a bit to cover more cases):
```yaml
#
# Steering Wheel
#
### ** The leading '-' creates a list of objects **
- SteeringWheel: ### **This line creates a None type**
   instances:
     - Test[1,2]
     - Test[1,2]
  type: branch
  description: Steering wheel signals

### ** let's assume this should be a list **
- SteeringWheel.Angle:
  datatype: Int16
  type: sensor
  unit: degrees
  description: Steering wheel angle. Positive = degrees to the left. Negative = degrees to the right.

### ** Depth by .-separated string **
- SteeringWheel.Tilt:
  datatype: uint8
  type: actuator
  min: 0
  max: 100
  unit: percent
  description: Steering wheel column tilt. 0 = Lowest position. 100 = Highest position.

- SteeringWheel.Extension:
  datatype: uint8
  type: actuator
  min: 0
  max: 100
  unit: percent
  description: Steering wheel column extension from dashboard. 0 = Closest to dashboard. 100 = Furthest from dashboard.
```
Using `pyyaml` this results into the string beneath, and you can see actually all three problems from above.

```
[{'SteeringWheel': None, 'type': 'branch', 'instances': ['Test[1,2]', 'Test[1,2]'], 
'description': 'Steering wheel signals'},
 {'SteeringWheel.Angle': None, 'datatype': 'Int16', 'type': 'sensor', 'unit': 'degrees', 
'description': 'Steering wheel angle. Positive = degrees to the left. Negative = degrees to the right.'}, 
{'SteeringWheel.Tilt': None, 'datatype': 'uint8', 'type': 'actuator', 'min': 0, 'max': 100, 
'unit': 'percent', 'description': 'Steering wheel column tilt. 0 = Lowest position. 100 = Highest position.'}, 
{'SteeringWheel.Extension': None, 'datatype': 'uint8', 'type': 'actuator', 'min': 0, 'max': 100, 
'unit': 'percent', 'description': 'Steering wheel column extension from dashboard. 0 = Closest to dashboard. 100 = Furthest from dashboard.'}]
```

The new proposal could change the original spec like the following:
* Don't use top level lists
* Nest objects, if there is a hierarchy
* Use Yaml lists to actually describe lists

```yaml
#
# Steering Wheel
#
### ** Defines a real object **
SteeringWheel:
  type: branch
  instances:
    - Row[1,2]
    - test
  description: Steering wheel signals
  
  ### ** Depth through indent **
  Angle: 
    - datatype: Int16 ### ** list defined through standard yaml (would be possible in the version above as well **
      type: sensor
      unit: degrees
      description: Steering wheel angle. Positive = degrees to the left. Negative = degrees to the right.

  Tilt:
    datatype: uint8
    type: actuator
    min: 0
    max: 100
    unit: percent
    description: Steering wheel column tilt. 0 = Lowest position. 100 = Highest position.

  Extension:
      datatype: uint8
      type: actuator
      min: 0
      max: 100
      unit: percent
      description: Steering wheel column extension from dashboard. 0 = Closest to dashboard. 100 = Furthest from dashboard.
```

Tis results into:
```
{'SteeringWheel': {'type': 'branch', 'instances': ['Row[1,2]', 'test'], 
'description': 'Steering wheel signals', 
'Angle': [{'datatype': 'Int16', 'type': 'sensor', 'unit': 'degrees', 'description': 'Steering wheel angle. Positive = degrees to the left. Negative = degrees to the right.'}], 
'Tilt': {'datatype': 'uint8', 'type': 'actuator', 'min': 0, 'max': 100, 'unit': 'percent', 'description': 'Steering wheel column tilt. 0 = Lowest position. 100 = Highest position.'}, 
'Extension': {'datatype': 'uint8', 'type': 'actuator', 'min': 0, 'max': 100, 'unit': 'percent', 'description': 'Steering wheel column extension from dashboard. 0 = Closest to dashboard. 100 = Furthest from dashboard.'}}}
```

What's still open how to handle includes, but I would handle that in a separate issue.

**Comment by gunnarx** [comment]
In my opinion, yes, each signal must be an independent object in each file.
So therefore the '-' should be removed
```
- SteeringWheel: ### **This line creates a None type**
```
becomes
```
SteeringWheel:
```

Then, for nesting I think it would be acceptable to have both:

1. According to Daniel's example above
```
SteeringWheel:  # Is really <something>.SteeringWheel - the <something> is defined by where this file was inserted into the tree.
  type: branch
  ...  
  ### ** Depth through indent **
  Angle:    #  Is really <something> SteeringWheel.Angle, i.e. a submode to SteeringWheel
```
but also:
2. Fully or partially qualified names:
```
SteeringWheel:
   type: branch
   ...
# No indentation...
SteeringWheel.Angle:
   ...
SteeringWheel.Tilt:
   ...
```
This is more similar to what VSS is today.   Are both of these possible to allow at the same time?

**Comment by gunnarx** [comment]
Actually on second thought I'm not sure I accept this:

```
SteeringWheel:  # Is really <something>.SteeringWheel - the <something> is defined by where this file was inserted into the tree.
  type: branch
  description:  This is the steering wheel
  ### ** Depth through indent **
  Angle:
     type: signal
     description: Measured angle of steering wheel from 0 to 540 degrees
     <more metadata for Angle>
```
Because it puts a subnode (Angle) on the same level as metadata.  This does not match, I feel:
  - the metadata topic names are "fixed" and known beforehand, and the same for all (most) nodes, (depending on layers and stuff of course)
  - But the signal name is unknown name until it suddently appears here
  - Signal definitions and metadata do not feel like the same type of information?
  - How would you be 100% sure which is a sub-node definition and which is just metadata?  And avoid clashes - you might have a "metadata" named Angle?

So make it like a consistently traversable model and guarantee no collision you would normally do something like putting the children under a particular metadata topic so you know where to find them:

```
Steering: 
   type: ...
   description: ...
   children :  
        - Angle:
          type: foo
          description: bar
```
but going down this road looks ugly to me.  It makes the children into a list / array which we seemed to want to avoid in the first place, and all of this does not seem to scale very nicely.  Can we find another way?

**Comment by gunnarx** [comment]
>    Don't use top level lists

Agree in principle, unless we're forced to, to be able to have more than one signal per file and also be able to parse the file.   

>    Nest objects, if there is a hierarchy

Also desirable, but in my opinion as an optional addition to a flat list.
But as shown above, I'm not sure that ends up being completely clean.

>    Use Yaml lists to actually describe lists

Yes.

Overall make sure we consider the "deployment file" we have talked about before.  It was preferrable there, some argued, to have a single file for *all* signals.    If that single file is to be coded as a VSS layer, then we must allow a reasonable way to allow valid VSS-formatted files (which layers are) to include every single signal.  If the format requires that to be written as a tree with one new indentation level for each branch level, then it becomes unmanageable.

**Comment by danielwilms** [comment]
> Because it puts a subnode (Angle) on the same level as metadata. This does not match, I feel:
>
> * the metadata topic names are "fixed" and known beforehand, and the same for all (most) nodes, (depending on layers and stuff of course)
> * But the signal name is unknown name until it suddently appears here
Signal definitions and metadata do not feel like the same type of information?
> * How would you be 100% sure which is a sub-node definition and which is just metadata? And avoid clashes - you might have a "metadata" named Angle?

I see, what you're saying, but I don't fully agree, thinking about it. as sugesstion:
* There can be a rule that all meta-data comes first
* a node is defined, by type, name and description. that sets a node apart from the meta-data
* there could be a keyword `meta`, which contains a dictionary of the meta information, for all non-mandatory fields

```
SteeringWheel:
  type: branch
  description: Steering wheel signals
  meta:
      instances:
        - Row[1,2]
        - test
 
  ### ** Depth through indent **
  Angle: 
    - type: sensor
      description: Steering wheel angle. Positive = degrees to the left. Negative = degrees to the right.
      meta: 
        datatype: Int16 ### ** list defined through standard yaml (would be possible in the version above as well **
        type: sensor
        unit: degrees
 ```

> Overall make sure we consider the "deployment file" we have talked about before. It was preferrable there, some argued, to have a single file for all signals. If that single file is to be coded as a VSS layer, then we must allow a reasonable way to allow valid VSS-formatted files (which layers are) to include every single signal. If the format requires that to be written as a tree with one new indentation level for each branch level, then it becomes unmanageable.

I saw the layers, as an instance between spec and 'compilation'. I just thought, if it doesn't conflict, it's just fine to use the normal spec for the additional meta-data as well. that would be something we have to think about. but first thought is, that the `meta` object would support that.
