### ISSUE TITLE
Inconsistency with attribute value vs. default

### ISSUE THREAD

**Issue by rfrowe** [GENIVI/vehicle_signal_specification#198]
The [documentation](https://genivi.github.io/vehicle_signal_specification/rule_set/data_entry/attributes/) states:
> An attribute is a signal with a default value, specified by its `value` member.

However, the example immediately below is:
```yaml
- MaxPower:
  type: attribute
  datatype:  uint16
  default: 0
  description: Peak power, in kilowatts, that engine can generate.
```

This example is noticeably lacking a `value` and instead a `default` has been specified. Looking at the specification itself, both `default` and `value` seem to be used interchangeably in different attributes to mean the same thing. 

For example:
```yaml
# From spec/Powertrain/EnergyStorage/FuelSystem.vspec
- HybridType:
  datatype: string
  type: attribute
  enum: [ "unknown", "not_applicable", "stop_start", "belt_ISG", "CIMG", "PHEV" ]
  default: "unknown"
  description: Defines the hybrid type of the vehicle
```

```yaml
# From spec/Chassis/Chassis.vspec
- CurbWeight:
  datatype: uint16
  type: attribute
  value: 0
  unit: kg
  description: Vehicle curb weight, in kg, including all liquids and full tank of fuel, but no cargo or passengers.
```

As such, the specification is inconsistent. All should use either `default` or `value`.
