### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by danielwilms** [GENIVI/vehicle_signal_specification#216]
Some nodes are moved with in the tree. Deprecation would be help to adapt. Therefore, the suggestion is to add a `deprecation` keyword to the nodes, which are moved. Using a keyword in the yaml node works nicely with the current tooling.

Example:
```
Navigation.CurrentLocation:
  type: branch
  aggregate: true
  description: The current latitude and longitude of the vehicle.
  deprication: @v2.1 moved to Vehicle.CurrentLocation
```
