### ISSUE TITLE
Meaning of "aggregate" for branches?

### ISSUE THREAD

**Issue by erikbosch** [GENIVI/vehicle_signal_specification#246]
In https://genivi.github.io/vehicle_signal_specification/rule_set/branches/ we describe aggregate. Well we do not describe it that well:

`Defines whether or not this branch is an aggregate. If not defined, this defaults to false.`

It is used in a few cases where data logically "belongs together". But do we know of any tooling actually relying on "aggregate" in any kind? Or is it just handled as informal information? I think it would be good to improve the documentation on "aggregate" and I can create a PR for that, but then I first need to understand the background for it, and make sure that we still consider it useful (otherwise we can deprecate it)

Example usage:
```
- CurrentLocation:
  type: branch
  aggregate: true
  description: The current latitude and longitude of the vehicle.
```
