### ISSUE TITLE
Signals of heavy-duty vehicle

### ISSUE THREAD

**Issue by iabtv** [GENIVI/vehicle_signal_specification#258]
Hello,

I'm working on a private branch with Signals of heavy-duty vehicle,  most of them refer to SAE J1939-71/73. Is there any plan add such signals to the standard branch? 

e.x. 
```
- Engine:
  type: branch
  description: Engine signals

- Engine.TorqueMode:
  datatype: string
  type: sensor
  enum: ['not_request', 'accelerator_pedal', 'cruise_control', 'pto_governor', 'road_speed_governor', 'asr_control', 'transmission_control',
  'abs_control', 'torque_limiting', 'high_speed_governor', 'braking_system', 'remote_accelerator', 'not_define', 'other', 'not_available']
  description: Reference SAE J1939-71 SPN899. State signal which indicates which engine torque mode is currently generating, limiting, or controlling the torque.

#
# Current percentage Torque
#
- Engine.ActualPercentTorque:
  datatype: uint8
  type: sensor
  unit: percent
  min: 0
  max: 125
  description: Reference SAE J1939-71 PGN61444/SPN513. The calculated output torque of the engine.


- Engine.IsCompressionReleaseActive:
  datatype: boolean
  type: actuator
  deescription: Indicates if the engine compression release control system is enalbed. True = Enabled. False = Disabled.

```
