### ISSUE TITLE
Adding Seat Position Actuators

### ISSUE THREAD

**Issue by erikbosch** [GENIVI/vehicle_signal_specification#315]
In https://github.com/GENIVI/vehicle_signal_specification/blob/master/spec/Cabin/SingleSeat.vspec we have numerous signals for controlling seats. Typically each feature consist of one sensor and two boolean actuator switches to change the value. Below is an example for position. 

This works quite well if you have e.g. an app with buttons to move a seat forward/backward (with speed defined by vehicle), but it might not work that well if you want to move the seat to a previously set position, then it would be easier to be able to request an absolute position. This could be easily achieved by changing Position from sensor to actuator. 

_Does anyone have any objection changing Position and similar seat signals from sensors to actuators?_

(I.e. keeping the Forward/Backward actuators as an alternative method to move the seat)

```
Position:
  datatype: uint16
  type: sensor
  min: 0
  max: 1000
  unit: mm
  description: Seat horizontal position. 0 = Frontmost. 1000 = Rearmost

Switch.Forward:
  datatype: boolean
  type: actuator
  description: Seat forward switch engaged

Switch.Backward:
  datatype: boolean
  type: actuator
  description: Seat forward switch engaged
```
